apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: welcome-php
  name: welcome-php
  namespace: kapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-php
  strategy: {}
  template:
    metadata:
      labels:
        app: welcome-php
    spec:
      containers:
      - image: quay.io/redhatworkshops/welcome-php
        name: welcome-php
        resources: {}
      - image: docker.io/library/registry:3.0.0-alpha.1
        name: registry
        resources: {}
